;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-word
        cua-paste
        markdown-outdent-or-delete
        mwim-beginning
        mwim-end
        org-cycle
        org-insert-heading-respect-content
        org-metaleft
        org-metaright
        org-return-indent
        org-self-insert-command
        org-shiftcontrolright
        org-shiftmetaleft
        org-shiftmetaright
        org-shiftright
        ))

(setq mc/cmds-to-run-once
      '(
        ))
