;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        abbrev-prefix-mark
        backward-delete-word
        cua-copy-handler
        cua-copy-region
        cua-paste
        delete-word
        markdown-outdent-or-delete
        mwim-beginning
        mwim-end
        olivetti-mode
        org-cycle
        org-demote-subtree
        org-insert-heading-respect-content
        org-meta-return
        org-metaleft
        org-metaright
        org-return
        org-return-indent
        org-self-insert-command
        org-shiftcontrolleft
        org-shiftcontrolright
        org-shiftmetaleft
        org-shiftmetaright
        org-shiftright
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-switch-buffer
        switch-to-buffer
        ))
